name: 'dbt_sparkify'
version: '1.0.0'

profile: 'dbt_sparkify'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_sparkify:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts